export const userData = [
  {
    id: 1,
    name: "Alice Johnson",
    designation: "Teacher",
    email: "alice.johnson@example.com",
    schoolName: "Greenwood High School",
    location: "New York, USA",
    income: 55000,
    image: "https://randomuser.me/api/portraits/women/1.jpg",
    contactNo: "+1 123-456-7890",
    address: "123 Maple Street, New York, NY 10001, USA",
    type: "Free",
    userType: "Teacher", // Added userType
  },
  {
    id: 2,
    name: "Bob Smith",
    designation: "Principal",
    email: "bob.smith@example.com",
    schoolName: "Sunnydale Academy",
    location: "California, USA",
    income: 75000,
    image: "https://randomuser.me/api/portraits/men/2.jpg",
    contactNo: "+1 234-567-8901",
    address: "456 Oak Avenue, Los Angeles, CA 90001, USA",
    type: "Free",
    userType: "Admin", // Principal as Admin
  },
  {
    id: 3,
    name: "Charlie Brown",
    designation: "Math Teacher",
    email: "charlie.brown@example.com",
    schoolName: "Hilltop School",
    location: "Texas, USA",
    income: 48000,
    image: "https://randomuser.me/api/portraits/men/3.jpg",
    contactNo: "+1 345-678-9012",
    address: "789 Pine Road, Dallas, TX 75001, USA",
    type: "Free",
    userType: "Teacher",
  },
  {
    id: 4,
    name: "David Lee",
    designation: "Science Teacher",
    email: "david.lee@example.com",
    schoolName: "Riverdale High",
    location: "Florida, USA",
    income: 52000,
    image: "https://randomuser.me/api/portraits/men/4.jpg",
    contactNo: "+1 456-789-0123",
    address: "101 Birch Lane, Miami, FL 33101, USA",
    type: "Premium",
    userType: "Teacher",
  },
  {
    id: 5,
    name: "Emma Watson",
    designation: "History Teacher",
    email: "emma.watson@example.com",
    schoolName: "Springfield School",
    location: "Illinois, USA",
    income: 49000,
    image: "https://randomuser.me/api/portraits/women/5.jpg",
    contactNo: "+1 567-890-1234",
    address: "202 Cedar Drive, Springfield, IL 62701, USA",
    type: "Premium",
    userType: "Teacher",
  },
  {
    id: 6,
    name: "Frank Castle",
    designation: "Sports Coach",
    email: "frank.castle@example.com",
    schoolName: "Westwood Academy",
    location: "Ohio, USA",
    income: 53000,
    image: "https://randomuser.me/api/portraits/men/6.jpg",
    contactNo: "+1 678-901-2345",
    address: "303 Elm Street, Columbus, OH 43201, USA",
    type: "Premium",
    userType: "Teacher", // Coach as Teacher
  },
  {
    id: 7,
    name: "Grace Miller",
    designation: "English Teacher",
    email: "grace.miller@example.com",
    schoolName: "Lakeside High",
    location: "Michigan, USA",
    income: 51000,
    image: "https://randomuser.me/api/portraits/women/7.jpg",
    contactNo: "+1 789-012-3456",
    address: "404 Maple Avenue, Detroit, MI 48201, USA",
    userType: "Teacher",
  },
  {
    id: 8,
    name: "Henry Adams",
    designation: "Music Teacher",
    email: "henry.adams@example.com",
    schoolName: "Evergreen Academy",
    location: "Washington, USA",
    income: 47000,
    image: "https://randomuser.me/api/portraits/men/8.jpg",
    contactNo: "+1 890-123-4567",
    address: "505 Pine Street, Seattle, WA 98101, USA",
    type: "Premium",
    userType: "Teacher",
  },
  {
    id: 9,
    name: "Isabella Roberts",
    designation: "Art Teacher",
    email: "isabella.roberts@example.com",
    schoolName: "Sunset High School",
    location: "Arizona, USA",
    income: 46000,
    image: "https://randomuser.me/api/portraits/women/9.jpg",
    contactNo: "+1 901-234-5678",
    address: "606 Oak Road, Phoenix, AZ 85001, USA",
    type: "Premium",
    userType: "Teacher",
  },
];
export const fakeSubscribers = [
  {
    id: 1,
    image: "https://randomuser.me/api/portraits/men/1.jpg",
    name: "John Doe",
    designation: "Professor",
    email: "john.doe@example.com",
    subject: "Mathematics",
  },
  {
    id: 2,
    image: "https://randomuser.me/api/portraits/women/2.jpg",
    name: "Jane Smith",
    designation: "Lecturer",
    email: "jane.smith@example.com",
    subject: "History",
  },
  {
    id: 3,
    image: "https://randomuser.me/api/portraits/men/3.jpg",
    name: "Michael Brown",
    designation: "Assistant Teacher",
    email: "michael.brown@example.com",
    subject: "English",
  },
  {
    id: 4,
    image: "https://randomuser.me/api/portraits/women/4.jpg",
    name: "Emily Johnson",
    designation: "Tutor",
    email: "emily.johnson@example.com",
    subject: "Physics",
  },
  {
    id: 5,
    image: "https://randomuser.me/api/portraits/men/5.jpg",
    name: "Robert Wilson",
    designation: "Senior Lecturer",
    email: "robert.wilson@example.com",
    subject: "Chemistry",
  },
  {
    id: 6,
    image: "https://randomuser.me/api/portraits/women/6.jpg",
    name: "Sophia Martinez",
    designation: "Head of Department",
    email: "sophia.martinez@example.com",
    subject: "Biology",
  },
  {
    id: 7,
    image: "https://randomuser.me/api/portraits/men/7.jpg",
    name: "David Anderson",
    designation: "Research Scholar",
    email: "david.anderson@example.com",
    subject: "Geography",
  },
  {
    id: 8,
    image: "https://randomuser.me/api/portraits/women/8.jpg",
    name: "Olivia White",
    designation: "Teaching Assistant",
    email: "olivia.white@example.com",
    subject: "Economics",
  },
  {
    id: 9,
    image: "https://randomuser.me/api/portraits/men/9.jpg",
    name: "James Thompson",
    designation: "Academic Counselor",
    email: "james.thompson@example.com",
    subject: "Political Science",
  },
  {
    id: 10,
    image: "https://randomuser.me/api/portraits/women/10.jpg",
    name: "Emma Brown",
    designation: "Private Tutor",
    email: "emma.brown@example.com",
    subject: "Psychology",
  },
];
export const fakeStudents = [
  {
    id: "S001",
    name: "Aiden Carter",
    grade: "8th Grade",
    age: 14,
    stage: "Middle School",
    strainLevel: "Moderate",
    emotionalStatus: "Happy",
    image: "https://randomuser.me/api/portraits/men/1.jpg", // Example image URL
  },
  {
    id: "S002",
    name: "Sophia Green",
    grade: "10th Grade",
    age: 16,
    stage: "High School",
    strainLevel: "High",
    emotionalStatus: "Stressed",
    image: "https://randomuser.me/api/portraits/women/2.jpg", // Example image URL
  },
  {
    id: "S003",
    name: "Liam Brown",
    grade: "6th Grade",
    age: 12,
    stage: "Elementary School",
    strainLevel: "Low",
    emotionalStatus: "Excited",
    image: "https://randomuser.me/api/portraits/men/3.jpg", // Example image URL
  },
  {
    id: "S004",
    name: "Olivia Johnson",
    grade: "9th Grade",
    age: 15,
    stage: "High School",
    strainLevel: "Moderate",
    emotionalStatus: "Calm",
    image: "https://randomuser.me/api/portraits/women/4.jpg", // Example image URL
  },
  {
    id: "S005",
    name: "Ethan Miller",
    grade: "7th Grade",
    age: 13,
    stage: "Middle School",
    strainLevel: "High",
    emotionalStatus: "Anxious",
    image: "https://randomuser.me/api/portraits/men/5.jpg", // Example image URL
  },
  {
    id: "S006",
    name: "Emma Wilson",
    grade: "5th Grade",
    age: 11,
    stage: "Elementary School",
    strainLevel: "Low",
    emotionalStatus: "Cheerful",
    image: "https://randomuser.me/api/portraits/women/6.jpg", // Example image URL
  },
  {
    id: "S007",
    name: "James Anderson",
    grade: "11th Grade",
    age: 17,
    stage: "High School",
    strainLevel: "Very High",
    emotionalStatus: "Frustrated",
    image: "https://randomuser.me/api/portraits/men/7.jpg", // Example image URL
  },
  {
    id: "S008",
    name: "Mia Thomas",
    grade: "4th Grade",
    age: 10,
    stage: "Elementary School",
    strainLevel: "Moderate",
    emotionalStatus: "Relaxed",
    image: "https://randomuser.me/api/portraits/women/8.jpg", // Example image URL
  },
];

export default fakeStudents;

export const schoolData = [
  {
    school_name: "Green Valley High",
    email: "contact@greenvalley.edu",
    location: "California, USA",
    type: "Public",
    income_package_name: "Basic Plan",
    package_price: "$500/month",
    income: 55000,
    school_image:
      "https://via.placeholder.com/150/009688/ffffff?text=Green+Valley+High",
  },
  {
    school_name: "Riverside Academy",
    email: "info@riversideacademy.com",
    location: "Texas, USA",
    type: "Private",
    income_package_name: "Advanced Plan",
    package_price: "$800/month",
    income: 55000,
    school_image:
      "https://via.placeholder.com/150/3F51B5/ffffff?text=Riverside+Academy",
  },
  {
    school_name: "Sunrise International School",
    email: "support@sunriseintl.org",
    location: "London, UK",
    type: "International",
    income_package_name: "Premium Plan",
    package_price: "$1000/month",
    income: 55000,
    school_image:
      "https://via.placeholder.com/150/FF9800/ffffff?text=Sunrise+International+School",
  },
  {
    school_name: "Maple Leaf Academy",
    email: "admissions@mapleleafacademy.ca",
    location: "Toronto, Canada",
    type: "Private",
    income_package_name: "Standard Plan",
    package_price: "$600/month",
    income: 55000,
    school_image:
      "https://via.placeholder.com/150/8BC34A/ffffff?text=Maple+Leaf+Academy",
  },
  {
    school_name: "Hilltop Secondary School",
    email: "contact@hilltopsec.edu",
    location: "Sydney, Australia",
    type: "Public",
    income_package_name: "Basic Plan",
    package_price: "$400/month",
    income: 55000,
    school_image:
      "https://via.placeholder.com/150/607D8B/ffffff?text=Hilltop+Secondary+School",
  },
];
